### ISSUE TITLE
Investigate stream deployment issues

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-admin-kubernetes#39]
As a user, I'm trying to deploy streams both in local and on GCE, but I've trouble getting it to deploy with the config options provided in the docs. 

**Acceptance:**
- I can successfully deploy a `ticktock` stream both locally and GCE
- Isolate the required config changes for successful deployment
- Update docs with config changes

**Comment by trisberg** [comment]
This seems to be related to the cloud monitoring, if I create the cluster using `--no-enable-cloud-monitoring` then the stream deploys. If cloud monitoring is enabled I can't get the apps to start. It seems to take a long time to start an app, maybe I should try using beefier nodes.

I also tried modifying the `--kubernetes.readinessProbeDelay`, `--kubernetes.readinessProbeTimeout`, `--kubernetes.livenessProbeDelay` and `--kubernetes.livenessProbeTimeout` settings but the apps are still restarted after approximately 1min.
