### ISSUE TITLE
Add integration-tests for K8S SPI 

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-admin-kubernetes#6]
As a developer, I'd like to continuously test and evaluate k8S SPI capabilities using `local` SPI as part of the CI plan.

**Acceptance:**
* K8S' Integration tests run successfully on each code commit
* Installation steps and gotchas are documented in the `README` / ref. guide

**Comment by markpollack** [comment]
I think it maybe enough for us to rely on the google container service for integration testing vs. standing up k8s on AWS.  Maybe we can change this issue to be CI integration tests that use a local install of k8s?

**Comment by sabbyanandan** [comment]
Sure, makes sense. Updated.

**Comment by sabbyanandan** [comment]
This is a duplicate of #9.
