### ISSUE TITLE
Add integration test environment for CI builds

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow-admin-kubernetes#9]
The AMI for our CI builds has docker/docker-compose.  Look to use https://github.com/vyshane/docker-compose-kubernetes as a way to bootstrap k8s on the local build box.

**Comment by ericbottard** [comment]
See https://github.com/spring-cloud/spring-cloud-dataflow/issues/292 (for actual tests, no the CI infrastructure per se)
